name: CI
on:
  workflow_dispatch:
  schedule:
    - cron: 20 4 * * 6

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Run get.sh 
        id: sh
        run: |
          sudo chmod +x get.sh
          source get.sh 1 2
          echo -e "- Version: $ARTIX_VERSION\n- [Extracted from weakly Artix releases official mirror](https://mirror1.artixlinux.org/weekly-iso/)\n" > release_body.txt
          echo "artix_version=$ARTIX_VERSION" >> $GITHUB_OUTPUT

      - name: Upload tarball as GitHub artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: artix_rootfs.tar.xz
          path: artix_rootfs.tar.xz
          if-no-files-found: error

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2.0.5
        with:
          name: ${{ steps.sh.outputs.artix_version }}
          tag_name: ${{ steps.sh.outputs.artix_version }}
          body_path: release_body.txt
          files: artix_rootfs.tar.xz
